services:
  api:
    build: .
    env_file:
      - .env
    environment:
      GRPC_MOCK_DB_TYPE: sqlite
    ports:
      - "${GRPC_MOCK_PORT}:${GRPC_MOCK_PORT}"
    command:
      - "${GRPC_MOCK_HOST}:${GRPC_MOCK_PORT}"
