services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${GRPC_MOCK_DATABASE_USER}
      POSTGRES_PASSWORD: ${GRPC_MOCK_DATABASE_PASSWORD}
      POSTGRES_DB: ${GRPC_MOCK_DATABASE_NAME}
    ports:
      - "${GRPC_MOCK_DATABASE_PORT}:5432"
