[project]
name = "grpc-mock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h2>=4.2.0",
    "hyperframe>=6.1.0",
]

[dependency-groups]
dev = [
    "betterproto[compiler]==2.0.0b7",
]
