[project]
name = "grpc-mock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "betterproto[compiler]==2.0.0b7",
]
